# Generated by Django 5.2.6 on 2025-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('robo', 'Robo'), ('violencia', 'Violencia'), ('acoso', 'Acoso'), ('ambiental', 'Riesgo Ambiental'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('anonimo', models.BooleanField(default=True)),
            ],
        ),
    ]
